#!/bin/bash
# Remove large .npy from git and re-push. Run from repo root.

set -e
cd "$(dirname "$0")"

echo "1. Remove test set files from git tracking (keep files on disk)..."
git rm --cached data/adhd/adhd_test_775.npy data/adhd/test_roi_matrices_775.npy 2>/dev/null || true

echo "2. Undo last commit (keep all changes in working tree)..."
git reset --soft HEAD~1

echo "3. Re-stage all changes (data/ is now in .gitignore, so .npy won't be added)..."
git add -A
git status

echo "4. Commit again without the large file..."
git commit -m "Smoke: 10-sample test set (6/2/2); test data generated by prepare_dummy_adhd.py, not in repo (GitHub 100 MB limit)"

echo "5. Push..."
git push origin main

echo "Done."
